remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Shabbir Marzban
description: Applied Scientist @ TomTom
show_downloads: true
google_analytics: UA-33271543-1
